name: snakemake
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - matplotlib
  - pandas
  - pip
  - seaborn
  - snakemake
  - pip:
    - https://github.com/MEGA-GO/Mega-GO/archive/feature/split-per-go-domain.zip
