name: snakemake
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - matplotlib
  - pandas
  - pip
  - seaborn
  - snakemake
  - pip:
     - https://github.com/MEGA-GO/MegaGO/archive/add_lin_metric.zip
